### ISSUE TITLE
Jeweler should provide top-level methods for listing files in the project.

### ISSUE THREAD

**Issue by postmodern** [technicalpickles/jeweler#143]
Considering that gemspecs are used to generate the actual raw `metadata.gz` within gems (actually GZiped YAML), I can see why many individuals want to hand edit a minimal gemspec. To facilitate this, Jeweler should provide top-level methods for querying information about the repository, such as `lib` or `data` files. This would prevent developers from including hardcoded boilerplate code which called `Dir.glob` or `git ls-files`.

**Comment by flajann2** [comment]
Closing this issue due to its age. If this is still a problem, please reopen or resubmit. Thanks.
