### ISSUE TITLE
git_base_dir false positives

### ISSUE THREAD

**Issue by dpw** [technicalpickles/jeweler#175]
Background: I keep my home dir in git, which means that I have a ~/.git dir.  But not all the dirs under my home dir are in git (many subtrees of my home dir are excluded in ~/.gitignore).  Some ruby projects under my home dir are in mercurial, some are bare dirs.

In Jeweler::Specification, set_jeweler_defaults will always chdir to git_base_dir, assuming that is the root of the ruby project.  So unless my ruby project is in git, git_base_dir will find my home dir, with predictably useless results.

As a resolution, I guesst that there should be some way when invoking Jeweler::Tasks.new from a Rakefile to set the actual base dir and to disable the git support.

**Comment by flajann2** [comment]
This is old and so closing it.
