### ISSUE TITLE
Creating illformed gemspec requirements

### ISSUE THREAD

**Issue by superplussed** [technicalpickles/jeweler#203]
I'm getting this error when I try to release a gem after installing it:

Invalid gemspec in [/usr/local/Cellar/ruby/1.9.2-p290/lib/ruby/gems/1.9.1/specifications/parsley2-0.1.0.gemspec]: Illformed requirement ["#<Syck::DefaultKey:0x007f87d2ead088> 2.2.2"]

I'm not sure if upgrading to 1.9.2 p290 has had any effect on this.

**Comment by flajann2** [comment]
No longer supporting 1.9 so closing this issue.
