### ISSUE TITLE
Is Nokogiri really required?

### ISSUE THREAD

**Issue by julik** [technicalpickles/jeweler#276]
So this is a long shot, but I thought I will try. I still have lots of gems that have to be usable on 1.8.7 (and they are actually used by people in that context, because most of them use older Linux). For instance, I have committed to keep the entire dependency graph of https://gemnasium.com/gems/tracksperanto 1.8.7-compatible. This is actually very easy to do for me (I just keep adding Travis configs for the new Ruby versions and move on), and has provided great longevity for the releases.

I do have problems with Jeweler requiring Nokogiri starting with 1.8.5. Currently I have more than 10 gems I had to lock down to Jeweler 1.8.4 because highline will not build on older Rubies at all. Plus, build times go up if gems are not cached.

However, locking down to 1.8.4 is currently problematic because I get this when I try to release:

    rake aborted!
    LoadError: cannot load such file -- rubygems/builder
    
    Tasks: TOP => release => gemcutter:release => build

So I would love to update mto a newer Jeweler, but I can't because then I kill 1.8.7 compatibility just because Jeweler has to go up.

I was wondering: is there actually a reason Nokogiri became a dependency, while everything worked fine off of REXML? Was there a reason a switchover to Nokogiri was _that_ necessary after all? 

Bear in mind: I love Jeweler and it is an essential part of my workflow, and I still [endorse it](http://live.julik.nl/2014/11/why-stick-to-jeweler) - just that particular problem has been nagging me for quite a while.

**Comment by technicalpickles** [comment]
On 1.8.7 support, Jeweler itself stopped supporting it back in 2.0.1 over a year ago: https://github.com/technicalpickles/jeweler/pull/255

It's an old enough project I don't even know off hand if there was an explicit reason for nokogiri. A quick [code search](https://github.com/technicalpickles/jeweler/search?q=nokogiri&type=Code&utf8=%E2%9C%93) doesn't show anywhere using it. It may be a vestigial dependency, or it might be a dependency's dependency.

Might be worth experimenting in a branch to remove the dependency to see if things still work without it.

**Comment by julik** [comment]
That is actually fine, because then I can take my deps up to 2.0.1. I am not necessarily in favor of bringing back 1.8.7 support, but I will investigate the Nokogiri dep if you don't mind then.

**Comment by flajann2** [comment]
Closing since 1.x is no longer supported.
