### ISSUE TITLE
$SAFE setting incompatable with Ruby 2.3.0

### ISSUE THREAD

**Issue by lordalveric** [technicalpickles/jeweler#278]
https://github.com/technicalpickles/jeweler/blob/master/lib/jeweler/gemspec_helper.rb#L51

$SAFE values 2 thru 4 are now obsolete with Ruby 2.3.0. As a result I get this when I attempt to do "rake gemspec --trace":

    $ rake gemspec --trace
    ** Invoke gemspec (first_time)
    ** Invoke gemspec:generate (first_time)
    ** Invoke version_required (first_time)
    ** Execute version_required
    ** Execute gemspec:generate 
    Generated: rubyneat.gemspec
    ** Invoke gemspec:validate (first_time)
    ** Invoke gemspec_required (first_time)
    ** Execute gemspec_required
    ** Execute gemspec:validate
    rubyneat.gemspec is invalid. See the backtrace for more details.
    rake aborted!
    ArgumentError: $SAFE=2 to 4 are obsolete
    rubyneat.gemspec:1:in `block in parse'
    /home/alveric/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/jeweler-  2.0.1/lib/jeweler/gemspec_helper.rb:51:in `eval'
    /home/alveric/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/jeweler-2.0.1/lib/jeweler/gemspec_helper.rb:51:in `block in parse'
    Tasks: TOP => gemspec => gemspec:validate

**Comment by weshatheleopard** [comment]
Can you please merge this and release the new version of the gem? You are blocking our releases...

**Comment by technicalpickles** [comment]
I apologize for not being a more active maintainer. I need help, and have filed https://github.com/technicalpickles/jeweler/issues/283 to figure out the future of jeweler.

 In the short term, people could consider either using @steakknife's fork in https://github.com/technicalpickles/jeweler/pull/281, or https://github.com/flajann2/juwelier

**Comment by rdp** [comment]
another option: use jruby which ignores SAFE directives (FWIW :)

**Comment by flajann2** [comment]
This problem was fixed long ago. Thanks.
