### ISSUE TITLE
Is the gem abandoned? Last commit was made in May 2014.

### ISSUE THREAD

**Issue by weshatheleopard** [technicalpickles/jeweler#280]

**Comment by technicalpickles** [comment]
I'm not actively working on it. I try to follow the [The Pull Request Hack](http://felixge.de/2013/03/11/the-pull-request-hack.html) so I've added other contributors as people make PRs that can be merged.

**Comment by weshatheleopard** [comment]
There's a bunch of open merge requests right now. In particular, https://github.com/technicalpickles/jeweler/pull/279 is mission critical for me now as it breaks `bundler` on `ruby 2.3.0`.

**Comment by tadman** [comment]
I find this tool really useful and I've built a number of gems with it, I enjoy the simplicity.

Thanks for inviting others to help. I'd rather keep using Jeweler than switch to some janky alternative.

**Comment by weshatheleopard** [comment]
@technicalpickles: what about `rubygems.org` access so contributes can release the update versions?

**Comment by technicalpickles** [comment]
> what about rubygems.org access so contributes can release the update versions?

I'm fine with that, and pretty sure I give access to that so new contributors can merge & release their improvents. I don't want to be a blocker. I'm writing up an issue to hand off jeweler now.

**Comment by flajann2** [comment]
I've taken over maintenance of this gem.
