### ISSUE TITLE
Future of jeweler

### ISSUE THREAD

**Issue by technicalpickles** [technicalpickles/jeweler#283]
I don't use jeweler anymore, and haven't done any active work on it in a few years. I could say I don't have time for it, but that's not quite true, but it's definitely a matter of not being a priority for me.

I see a couple possibilities:

* mark the repository as abandoned, and recommend alternatives
* find the most active fork, and make them the 'canonical' fork

For the latter, there have been forks that take on different names. I'd be happy to let one of those be the canonical fork, but I'd just like to see either:

* deprecate their forked name (ie give a warning), update to rename back to jeweler
* deprecate jeweler, and direct to the renamed fork so there's an upgrade path

I might have cared about the 'jeweler' legacy at some point and it staying attached to my name, but at this point I'd be just happy to see it actively maintained and in new, caring hands.

cc https://github.com/technicalpickles/jeweler/issues/280 https://github.com/technicalpickles/jeweler/pull/281 @steakknife @flajann2

**Comment by technicalpickles** [comment]
I'm going to close out stale & PRs issues in preparation for this.

**Comment by technicalpickles** [comment]
I updated the README and repository description to indicate as unmaintained  with a link to here.

**Comment by technicalpickles** [comment]
I made a gitter room if anyone wants to talk about this in real time: https://gitter.im/technicalpickles/jeweler

**Comment by technicalpickles** [comment]
Another thought: if no one person is able to commit, but a few people can commit, I can make an open source organization (jeweler is taken, but jewelerrb is available). Or, that might easier to manage in any event.

**Comment by weshatheleopard** [comment]
@technicalpickles: as I said, I think I can take over minor maintenance (such as merging pull requests, and doing releases on rubygems) if you grant me respective permissions.

Not planning to do active development, I have `rubyXL` to work on (beside my primary job) but since I'm using jeweler, I obviously have interest to keep it functional.

**Comment by technicalpickles** [comment]
I said this in gitter, but I've added @weshatheleopard as a collaborator ✨

**Comment by leifcr** [comment]
@technicalpickles & @weshatheleopard, I suggest to have a look at @flajann2's juwelier here: https://github.com/flajann2/juwelier

It works fine in 2.3 and has a few changes/improvements already.

It might be easier to merge parts of that into jeweler, or just point to that fork?

**Comment by leifcr** [comment]
I tried @steakknife's fork as well, and it works just as well on the master branch.

**Comment by technicalpickles** [comment]
@leifcr I think the main 'problem' with juwelier is that it changes the namespace from `Jeweler` to `Juwelier`, which makes a migration path harder, and any potentially more difficult. One option might be to change jeweler to depend on juwelier, and just provide an API wrapper around it with a deprecation notice.

**Comment by leifcr** [comment]
@technicalpickles Agree

**Comment by flajann2** [comment]
https://github.com/flajann2/juwelier

I would be happy to take over Jeweler and maintain it. Indeed, I've forked it anyway. Or you can simply make Juwelier the "official" alternative.

**Comment by technicalpickles** [comment]
@flajann2 thank you, that would be great. I'll add you as a collaborator on this repo and on rubygems.org to start.

I'd be okay with making juewelier the official alternative, I just would worry about the upgrade path for existing users. Here's the path I'm imagining, for whichever is sunsetted:

* add compatibility namespace for the official thing (ie Jeweler to Juwelier, or viceversa)
* add a deprecation warning for the original namespace to indicate to use the official namespace, with a version that it will be removed (major release).

I'll let you decide which one would be easier. I'd vote for keeping the jeweler name because it'd probably be easier for users, but it might be more annoying to do the PR for it in the other direction.

**Comment by technicalpickles** [comment]
@flajann2 actually, you may need to let me know your RubyGems email address, because the one on your GitHub profile and in the juwelier.gemspec didn't work.

**Comment by francisluong** [comment]
Interesting... I hadn't considered the question of how rubygems.org handles transition when ownership over a gem is passed on.

**Comment by flajann2** [comment]
@technicalpickles , I updated my github settings.
Try: 
flajann2@users.noreply.github.com
or 
fred.mitchell@gmx.de

I will give some thoughts to the namespace issues, but what I might elect to do is to merge in my changes to Jeweler... except then I would have to bother the new Juwelier users to go back to Jeweler. So I am leaning more towards doing some basic maintenance on Jeweler and encouraging all to switch to Juwelier for more up-to-date and new features.

**Comment by flajann2** [comment]
Oh, RubyGems... haden't thought of the transistion issues there either. I found this:

http://guides.rubygems.org/command-reference/#gem-owner

**Comment by technicalpickles** [comment]
The rubygems.org transition isn't really a problem. Just adding new 'owners', which is done now.

> except then I would have to bother the new Juwelier users to go back to Jeweler.

Do you think there are more new Juwelier users, or existing Jeweler users? There are rubygems.org download stats, but those are for all time so it wouldn't be possible to account for any users that have found other solutions.

> I will give some thoughts to the namespace issues, but what I might elect to do is to merge in my changes to Jeweler. So I am leaning more towards doing some basic maintenance on Jeweler and encouraging all to switch to Juwelier for more up-to-date and new features.

If you are going to do that, you could make juwelier a dependency of jeweler, implement the namespace idea I was talking about, and have the jeweler files just print a deprecation notice.

**Comment by technicalpickles** [comment]
> https://rubygems.org/profiles/alveric , email for that: lordalveric@yahoo.com
>
>Seems one cannot easily change your Rubygems email! So much for consolidation!

flajann2@users.noreply.github.com didn't work (I wouldn't have expected it too). I was able to add fred.mitchell@gmx.de but `gem owner jeweler` was showing it as empty for some reason:

```
$ gem owner -a fred.mitchell@gmx.de jeweler
Owner added successfully.
Owners for gem: jeweler
- 
- <redacted>
- josh@technicalpickles.com
- <redacted>
- <redacted>
```

I tried lordalveric@yahoo.com too, but gem owner said it didn't exist. So maybe you were able to update the email address?

**Comment by flajann2** [comment]
Yes, I see jeweler showing up in my GitHub, as well as RubyGems Cool.

All looks good. I'll now take care of your brainchild. Many thanks.

**Comment by logicminds** [comment]
Why not just add commit access to these other developers instead of forking?

**Comment by flajann2** [comment]
It's a thought. For now, the pull request works.

**Comment by steakknife** [comment]
I only sent PRs to unblock work. I don't use jeweler either. Heck, I don't even use a gem I wrote for signing gems.

Ghetto copy&paste/muscle memory/scripts FTW.

**PS:** Github needs a community voting system for actual open source projects should maintainers, die, lose their passwords, go insane, etc. Fork is like 40% of the way there.
