### ISSUE TITLE
Update repo description with current status

### ISSUE THREAD

**Issue by patrickmclaren** [technicalpickles/jeweler#288]
The description currently reads

> Opinionated tool for creating and managing Rubygem projects. Unmaintained, see https://github.com/technicalpickles/jeweler/issues/283 for jeweler's future (if there is one)

Where #283 is now closed, and [README](https://github.com/technicalpickles/jeweler/blob/master/README.markdown) states that

> Jeweler maintenance has now shifted to Fred Mitchell. I am now maintaining both Jeweler and its fork, juwelier. I will keep Jeweler at least functional with the latest Ruby releases, but put new features in Juwelier. Your input on this is more than welcome.
>  &nbsp;
>   <snip>
>  &nbsp;
>   PLEASE NOTE that if you are starting afresh, please use the successor [Juwelier](https://github.com/flajann2/juwelier) I (Fred Mitchell, flajann2) will be maintaining both Jeweler and Juwelier, but will be adding new features to Juwelier, and eventually "merge" this one into Juwelier after some namespace issues are dealt with.

Could the repo description be updated to explain that the project is currently maintained, and perhaps that the project will be merged into Juwelier at some point?

**Comment by flajann2** [comment]
This has now been fixed.
