### ISSUE TITLE
Failing builds on dependent projects due too strict Ruby version requirement

### ISSUE THREAD

**Issue by julik** [technicalpickles/jeweler#299]
After the update for the `dependencies_for` that I have PRed the new Jeweler version has instated a constraint on my code that

> Gem::InstallError: jeweler requires Ruby version >= 2.2.2.

This broke tests for all libraries that work perfectly fine with 2.1 and 2.2 < 2.2.2. This was not expected TBH. Is there a specific reason this threshold was chosen?  I do see a7de79e6ef3c9f2f54b07bdef48a5da23c12affa but there is no explanation why this compatibility threshold needed raising. Maybe there is just some specific dependency that is playing up?

**Comment by flajann2** [comment]
Some things have shifted. Are you not able to upgrade yet? I will look into this.

**Comment by julik** [comment]
Not that I can't upgrade, but the problem is that many of my projects run on older Ruby versions too, and due to the Jeweler bump for Bundler compatibility they now suddenly require a fresh Ruby for any Rakefile operation. This is an unwelcome side-effect.

**Comment by flajann2** [comment]
I understand. I revved it because their were some incompatibilities I ran into with anything pre 2.2.5. Let me back-rev this to 2.2.2, but it may cause some problems... we'll see.

**Comment by flajann2** [comment]
Done. new Jeweler release 2.3.3
